services:
  scrapyd-deploy:
    image: scrapyd
    ports:
      - 6800:6800
    volumes:
      - ./projects:/projects
      - ./scrapyd:/scrapyd
      - /srv/data/datasette:/mnt
    environment:
      DB_CONNECTION_DIR: /mnt
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:6800/daemonstatus.json"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  scrapyd-web-deploy:
    image: scrapydweb
    volumes:
      - ./projects:/projects
      - ./scrapyd:/scrapyd
    ports:
      - 5000:5000
    environment:
      - SCRAPYD_SERVERS=scrapyd-deploy:6800
      - SCRAPY_PROJECTS_DIR=/projects
      - DATABASE_URL=sqlite:////scrapyd/database/db.sqlite3
      - DATA_PATH=/scrapyd
    depends_on:
      scrapyd-deploy:
        condition: service_healthy
